name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm run dev
          browser: chrome
          headless: true
      - name: Upload to S3
        run: |
          aws s3 sync ./cypress/screenshots/home-page/homepage.spec.js/homepage.png s3://hospital-landing-page-testing-artifacts
        env:
          AWS_ACCESS_KEY_ID: 'AKIAZ672R2PNSHLYTT7J'
          AWS_SECRET_ACCESS_KEY: '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'
          AWS_DEFAULT_REGION: 'ap-southeast-1'